"""Regenerate the attribute reference tables from the live attribute registry.

The registry in `tlang.attribute_handlers.SPECS` is the single source of truth for
every attribute's scope, applicable stages, and argument schema. Writing the
reference by hand would let it drift the moment someone adds a row, so both the
project docs and the bundled agent skill are generated from it instead.

Run from the repo root after changing any AttrSpec:

    python scripts/gen_attribute_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / 'src'))

from tlang.frontend.attribute_handlers import REGISTRY          # noqa: E402
from tlang.frontend.attribute_registry import generate_docs     # noqa: E402

BANNER = '<!-- GENERATED by scripts/gen_attribute_docs.py -- do not edit by hand. -->'

TARGETS = {
    ROOT / 'docs' / 'attribute-reference.md': """# Attribute reference

{banner}

Every attribute tlang understands, generated from the registry that also drives
parsing and validation, so this table cannot drift from the implementation.

**Scope** is where the attribute may be written: `global` attributes sit at file
level and attach to the *next* function; `function-body` attributes are pragmas
written inside a function. Using one in the wrong place is a build error naming
the correct scope.

**Stages** lists which shader stages accept the attribute. `any` means it is not
stage-specific. Using a stage-specific attribute on the wrong stage is a build
error that names the stages it *is* valid on.

**Params** shows each argument's name, type, permitted values (`∈ {{...}}`) and
default. Values are coerced to the declared type, so `[frag(early_tests=false)]`
is a real boolean `False`, not the truthy string `"false"`.

{table}
""",
    ROOT / 'plugins' / 'tlang' / 'skills' / 'tlang' / 'references' / 'attributes.md': """# tlang attribute reference

{banner}

Scope `global` = written at file level, attaches to the **next** function.
Scope `function-body` = a pragma written inside a function body.

Stage-specific attributes raise a build error naming the valid stages if used
elsewhere. Arguments are coerced to the declared type, and values outside
`∈ {{...}}` are rejected with the legal set listed.

{table}

## Notes that the table cannot express

- `[shader(...)]` and `[program(...)]` are the two that decide what gets built:
  a function without `[shader(...)]` is a plain helper, and a raster stage that
  no `[program(...)]` names is compiled and then discarded.
- `[include(m)]` and `[export]` work as a pair — `[include]` in the consumer,
  `[export]` on each helper function in the provider. Global-scope declarations
  (buffers, constants, `#define`) cross module boundaries with `[include]` alone.
- Bare marker attributes like `[triangles]` are shorthand for the equivalent
  stage-settings form (`[geom(in='triangles')]`). Both write the same slot, so
  the last one wins rather than conflicting.
- `[resourceblock(...)]` takes raw GLSL. Its `layout(...) in;`/`out;` lines
  conflict-check against the stage's generated layout, so you cannot silently
  emit two contradictory qualifiers.
""",
}


def main() -> int:
    table = generate_docs(REGISTRY)
    for path, template in TARGETS.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(template.format(banner=BANNER, table=table), encoding='utf-8')
        print(f'wrote {path.relative_to(ROOT)} ({len(table.splitlines())} attribute rows)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
